from pathlib import Path
import json, re

ROOT = Path(__file__).resolve().parents[1]
state = json.loads((ROOT / "governance/HAKIM_ACTIVE_STATE.json").read_text(encoding="utf-8"))
gradle = (ROOT / "app/build.gradle").read_text(encoding="utf-8")
promotion = json.loads((ROOT / "governance/PRODUCT_V1_PROMOTION_STATE.json").read_text(encoding="utf-8"))

def req(cond: bool, reason: str):
    if not cond:
        raise SystemExit("ACTIVE_STATE_GATE=FAIL reason=" + reason)

m = re.search(r"versionCode\s+(\d+)", gradle)
req(bool(m), "version_missing")
candidate = int(m.group(1))

req(state.get("single_source_of_truth") is True, "single_source")
req(state["cloud"]["last_verified_baseline_commit"] == "c84359e422dad0aa205f59a153a1f29d7f4c4e81", "cloud_baseline")
req(state["android"]["latest_source_parent"]["commit"] == "400fa406ba97208e02be157d1a13d5df1b713dec", "source_parent")
req(state["android"]["latest_source_parent"]["ci_run_number"] == 1042, "source_parent_ci")
req(state["android"]["candidate"]["version_code"] == candidate == 20302, "candidate_version")
req(state["android"]["candidate"]["field_verified"] is False, "field_must_remain_false")
req(state["android"]["candidate"]["promoted"] is False, "must_not_promote")
req(state["local_execution"]["phone_channel"] == "ONLINE_SIGNED_HEALTH_OBSERVED", "phone_claim")
req(state["local_execution"]["execution_fabric_source_integrated"] is True, "execution_fabric_source")
req(state["local_execution"]["execution_fabric_field_online"] is False, "must_not_claim_field_online")
req(state["local_execution"]["production_bridge_contract"] == "relay_result_topic+HR1", "bridge_contract")
req(state["local_execution"]["termux_channel"] == "NOT_PROVEN_CURRENTLY", "termux_claim")
field_version = int(state["android"]["field_observed_current"]["version_code"])
req(field_version >= 20106, "field_observed_version_floor")
req(field_version < candidate, "field_observed_must_precede_candidate")
req(state["android"]["field_observed_current"]["evidence"] == "signed_health_on_stateless_pairing", "field_observed_evidence")
req(state["android"]["field_observed_current"]["exact_public_source_mapping"] == "NOT_PROVEN", "field_source_mapping")
req(state["self_improvement"]["rollback_strategy"] == "FORWARD_ONLY_FROM_VERIFIED_BASELINE_SOURCE", "rollback_strategy")
req(state["self_improvement"]["d1_gate"] == "D1_MATERIAL_AVAILABLE_LOCAL_NOT_IN_CI", "d1_gate")
req(state["material_factory"]["physical_output_verified"] is False, "physical_claim")
req(state["human_biology"]["whole_body_systems_covered"] is True, "biology_coverage")
req(state["human_biology"]["brain_covered"] is True, "brain_coverage")
req(state["human_biology"]["heart_covered"] is True, "heart_coverage")
req(state["human_biology"]["autonomous_clinical_action"] is False, "clinical_autonomy")
req(state["human_biology"]["direct_intervention_requires_qualified_gate"] is True, "clinical_gate")
req(promotion.get("candidate_version") == candidate, "promotion_state_version")
req(promotion.get("promoted") is False, "promotion_state_must_be_false")
req(state["android"]["candidate"]["source_ci_state"] in {"PENDING_CURRENT_HEAD_CI", "SOURCE_CI_VERIFIED"}, "candidate_ci_state")
req(state["local_artifacts"]["worksheet_addition_within_10"] is True, "local_pdf_capability")
req(state["local_artifacts"]["openrouter_for_this_task"] is False, "local_pdf_no_openrouter")
req(state["local_artifacts"]["contextual_followup"] is True, "contextual_followup")
req(state["local_artifacts"]["last_artifact_memory"] is True, "last_artifact_memory")

print("ACTIVE_STATE_GATE=PASS")

req(state["tool_orchestration"]["silent_first"] is True, "silent_first")
req(state["tool_orchestration"]["embedded_browser_background"] is True, "embedded_browser_background")
req(state["tool_orchestration"]["browser_is_tool_not_terminal"] is True, "browser_not_terminal")
req(state["tool_orchestration"]["result_returns_to_hakim"] is True, "result_returns")
req(state["tool_orchestration"]["direct_url_content_local_by_default"] is True, "direct_url_privacy")
req(state["tool_orchestration"]["terminal_handoff_allowed"] is False, "terminal_handoff")

req(state["productization"]["candidate_version"] == 20302, "product_candidate")
req(state["productization"]["primary_ui_productized"] is True, "product_ui")
req(state["productization"]["technical_diagnostics_hidden"] is True, "product_diagnostics")
req(state["productization"]["sellable"] is False, "product_not_yet_sellable")

req(state["productization"]["raw_html_hidden"] is True, "raw_html_hidden")
req(state["productization"]["artifact_stream_hidden"] is True, "artifact_stream_hidden")
req(state["productization"]["generic_pdf_fallback"] is True, "generic_pdf_fallback")

req(state["local_artifacts"]["worksheet_subtraction_within_10"] is True, "subtraction_source")
req(state["local_artifacts"]["structured_spec_required"] is False, "structured_spec")
req(state["local_artifacts"]["worksheet_generic_pdf_fallback"] is True, "worksheet_generic_fallback")
req(state["local_artifacts"]["raw_model_dump_forbidden"] is True, "raw_model_dump")
req(state["productization"]["worksheet_generic_pdf_fallback"] is True, "product_worksheet_fallback")

req(state["local_artifacts"]["universal_artifact_pipeline"] is True, "universal_artifact_pipeline")
req(state["local_artifacts"]["content_render_separation"] is True, "content_render_separation")
req(state["local_artifacts"]["same_file_pdf_verification"] is True, "same_file_pdf_verification")
req(state["productization"]["universal_artifact_pipeline"] is True, "product_universal_artifact_pipeline")

req(state["productization"]["verified_multimodal_intake"] is True, "verified_multimodal_intake")
req(state["productization"]["exact_text_no_upload_fallback"] is True, "exact_text_fallback")
req(state["productization"]["visual_original_required"] is True, "visual_original_required")
req(state["productization"]["intake_field_verified"] is False, "intake_field_must_remain_false")
req(state["productization"]["photo_picker_scoped_media"] is True, "photo_picker_scoped_media")
req(state["productization"]["dedicated_file_provider"] is True, "dedicated_file_provider")
req(state["productization"]["attachment_content_evidence"] is True, "attachment_content_evidence")
req(state["productization"]["attachment_mime_conflict_gate"] is True, "attachment_mime_conflict_gate")
req(state["productization"]["attachment_cache_bound"] is True, "attachment_cache_bound")
req(state["productization"]["page_16k_ci_gate"] is True, "page_16k_ci_gate")
req(state["productization"]["d1_v2_structure_ci_gate"] is True, "d1_v2_structure_ci_gate")
req(state["productization"]["hardening_field_verified"] is False, "hardening_field_must_remain_false")
