from pathlib import Path
import json, re
ROOT=Path(__file__).resolve().parents[1]
def text(p): return (ROOT/p).read_text(encoding="utf-8")
def require(ok,msg):
    if not ok: raise SystemExit("P0: "+msg)
service=text("app/src/main/java/ps/hakim/phoneagent/HakimContinuityService.kt")
manifest=text("app/src/main/AndroidManifest.xml")
activity=text("app/src/main/java/ps/hakim/phoneagent/HakimAgentsChatActivity.kt")
boot=text("app/src/main/java/ps/hakim/phoneagent/BootReceiver.kt")
build=text("app/build.gradle")
policy=json.loads(text("governance/HAKIM_FIELD_SIGNING_IDENTITY.json"))
require("class HakimContinuityService : Service()" in service,"خدمة الاستمرارية مفقودة")
require("TICK_MS = 60_000L" in service,"نبض الاستمرارية ليس ٦٠ ثانية")
require("HakimConnectionResilience.schedule(app)" in service,"الخدمة لا تعيد تثبيت الجدولة")
require("return START_STICKY" in service,"الخدمة ليست START_STICKY")
require("startForeground(NOTIFICATION_ID" in service,"الخدمة لا تصبح foreground")
require("import android.webkit.WebView" not in service and "OkHttpClient" not in service and "https://ntfy.sh" not in service,"خدمة الاستمرارية تحمل شبكة/متصفح غير لازم")
m=re.search(r'<service\s+[^>]*android:name="\.HakimContinuityService"[^>]*>',manifest,re.S)
require(m is not None,"الخدمة غير معلنة في Manifest")
require('android:exported="false"' in m.group(0),"خدمة الاستمرارية أصبحت exported")
require('android:foregroundServiceType="remoteMessaging"' in m.group(0),"نوع foreground غير مثبت")
require("HakimContinuityService.ensure(this)" in activity,"الواجهة لا تثبت الاستمرارية عند الاستخدام")
require("HakimContinuityService.ensure(context)" in boot,"الإقلاع/التحديث لا يستعيد الاستمرارية")
vc=re.search(r"versionCode\s+(\d+)",build)
require(vc and int(vc.group(1))==20059,"الإصدار يجب أن يكون ٢٠٠٥٩")
require(policy["current_field_version"]==20058,"خط الميدان يجب أن يسجل ٢٠٠٥٨ المثبت")
require(policy["current_candidate_version"]==20059,"السياسة لا تسجل ٢٠٠٥٩")
require(policy["last_verified_field_version"]==20055,"آخر خط مقبول ميدانيًا يجب أن يبقى ٢٠٠٥٥")
require(policy["field_evidence"]["stability"]=="FAILED","فشل ٢٠٠٥٨ الميداني غير محفوظ")
require("TRANSHIBER" in policy["status"],"جذر OEM غير مثبت في الحالة")
print("HAKIM_20059_FOREGROUND_CONTINUITY=PASS")
print("HAKIM_20059_NO_NEW_NETWORK_OR_WEBVIEW=PASS")
print("HAKIM_20059_BOOT_AND_LAUNCHER_RECOVERY=PASS")
